// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function P(props) {
  return JsxRuntime.jsx("p", {
              children: props.children
            });
}

var make = P;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
