// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function PageTitle(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("h1", {
                          children: props.children,
                          className: "text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight"
                        }),
                    className: "min-w-0 flex-1"
                  }),
              className: "md:flex md:items-center md:justify-between"
            });
}

var make = PageTitle;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
