// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lingui from "../../locales/Lingui.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as LangProvider from "./LangProvider.res.mjs";
import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.res.mjs";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.res.mjs";

function parse(json) {
  var decoder = Json_Decode$JsonCombinators.object(function (field) {
        return {
                lang: field.optional("lang", Json_Decode$JsonCombinators.string),
                locale: field.optional("locale", Json_Decode$JsonCombinators.string)
              };
      });
  try {
    return Json$JsonCombinators.decode(json, decoder);
  }
  catch (exn){
    return {
            TAG: "Error",
            _0: "An unexpected error occurred when checking the id."
          };
  }
}

var RouteParams = {
  parse: parse
};

var LoaderArgs = {};

async function loader(param) {
  var lang = Core__Option.getOr(param.params.lang, "en");
  var locale = lang === "ja" ? "jp" : "us";
  Lingui.i18n.activate(lang);
  return {
          locale: locale,
          lang: lang
        };
}

var Component = LangProvider.make;

export {
  RouteParams ,
  LoaderArgs ,
  loader ,
  Component ,
}
/* Lingui Not a pure module */
