// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";

function Localized(props) {
  var query = ReactRouterDom.useLoaderData();
  return JsxRuntime.jsx(ReactRouterDom.Await, {
              children: props.children,
              resolve: query.i18nLoaders,
              errorElement: "Error loading translations"
            });
}

function loadMessages(lang, loadMessages$1) {
  var lang$1 = Core__Option.getOr(lang, "en");
  return Promise.all(loadMessages$1(lang$1));
}

var make = Localized;

export {
  make ,
  loadMessages ,
}
/* react-router-dom Not a pure module */
