// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function Localized$WaitForMessages(props) {
  var children = props.children;
  var query = ReactRouterDom.useLoaderData();
  var loaders = query.i18nLoaders;
  if (loaders !== undefined) {
    return JsxRuntime.jsx(ReactRouterDom.Await, {
                children: (function (param) {
                    return children();
                  }),
                resolve: Caml_option.valFromOption(loaders),
                errorElement: "Error loading translations"
              });
  } else {
    return children();
  }
}

var WaitForMessages = {
  make: Localized$WaitForMessages
};

function loadMessages(lang, loadMessages$1) {
  var lang$1 = Core__Option.getOr(lang, "en");
  return Promise.all(loadMessages$1(lang$1));
}

export {
  WaitForMessages ,
  loadMessages ,
}
/*  Not a pure module */
