// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "@lingui/core";

var Messages = {};

var i18n = Core.i18n;

var I18nProvider = {};

var Util = {};

var UtilString = {};

export {
  Messages ,
  i18n ,
  I18nProvider ,
  Util ,
  UtilString ,
}
/* i18n Not a pure module */
