// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as WaitForMessages from "../shared/i18n/WaitForMessages.re.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as CreateLocationEvent from "./CreateLocationEvent.re.mjs";
import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.re.mjs";
import * as CreateLocationEventPageQuery_graphql from "../../__generated__/CreateLocationEventPageQuery_graphql.re.mjs";

import { t } from '@lingui/macro'
;

var convertVariables = CreateLocationEventPageQuery_graphql.Internal.convertVariables;

var convertResponse = CreateLocationEventPageQuery_graphql.Internal.convertResponse;

var convertWrapRawResponse = CreateLocationEventPageQuery_graphql.Internal.convertWrapRawResponse;

var use = RescriptRelay_Query.useQuery(convertVariables, CreateLocationEventPageQuery_graphql.node, convertResponse);

var useLoader = RescriptRelay_Query.useLoader(convertVariables, CreateLocationEventPageQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(CreateLocationEventPageQuery_graphql.node, convertResponse, (function (prim) {
        return prim;
      }));

var $$fetch = RescriptRelay_Query.$$fetch(CreateLocationEventPageQuery_graphql.node, convertResponse, convertVariables);

var fetchPromised = RescriptRelay_Query.fetchPromised(CreateLocationEventPageQuery_graphql.node, convertResponse, convertVariables);

var retain = RescriptRelay_Query.retain(CreateLocationEventPageQuery_graphql.node, convertVariables);

var Query = {
  Operation: undefined,
  Types: undefined,
  convertVariables: convertVariables,
  convertResponse: convertResponse,
  convertWrapRawResponse: convertWrapRawResponse,
  use: use,
  useLoader: useLoader,
  usePreloaded: usePreloaded,
  $$fetch: $$fetch,
  fetchPromised: fetchPromised,
  retain: retain
};

function CreateLocationEventPage(props) {
  var data = ReactRouterDom.useLoaderData();
  var query = usePreloaded(data.data);
  return JsxRuntime.jsx(WaitForMessages.make, {
              children: (function () {
                  return Core__Option.getOr(Core__Option.map(query.location, (function ($$location) {
                                    return JsxRuntime.jsx(CreateLocationEvent.make, {
                                                location: $$location.fragmentRefs
                                              });
                                  })), t`Location doesn't exist.`);
                })
            });
}

var make = CreateLocationEventPage;

export {
  Query ,
  make ,
}
/*  Not a pure module */
