// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CreateEvent from "./CreateEvent.re.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.re.mjs";
import * as CreateEventPageQuery_graphql from "../../__generated__/CreateEventPageQuery_graphql.re.mjs";

var convertVariables = CreateEventPageQuery_graphql.Internal.convertVariables;

var convertResponse = CreateEventPageQuery_graphql.Internal.convertResponse;

RescriptRelay_Query.useQuery(convertVariables, CreateEventPageQuery_graphql.node, convertResponse);

RescriptRelay_Query.useLoader(convertVariables, CreateEventPageQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(CreateEventPageQuery_graphql.node, convertResponse, (function (prim) {
        return prim;
      }));

RescriptRelay_Query.$$fetch(CreateEventPageQuery_graphql.node, convertResponse, convertVariables);

RescriptRelay_Query.fetchPromised(CreateEventPageQuery_graphql.node, convertResponse, convertVariables);

RescriptRelay_Query.retain(CreateEventPageQuery_graphql.node, convertVariables);

function CreateEventPage(props) {
  var data = ReactRouterDom.useLoaderData();
  var query = usePreloaded(data.data);
  return JsxRuntime.jsx(CreateEvent.make, {
              locations: query.fragmentRefs
            });
}

var make = CreateEventPage;

export {
  make ,
}
/*  Not a pure module */
