// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.mjs";
import * as EventsStoryQuery_graphql from "../../__generated__/EventsStoryQuery_graphql.mjs";

var convertVariables = EventsStoryQuery_graphql.Internal.convertVariables;

var convertResponse = EventsStoryQuery_graphql.Internal.convertResponse;

var convertWrapRawResponse = EventsStoryQuery_graphql.Internal.convertWrapRawResponse;

var use = RescriptRelay_Query.useQuery(convertVariables, EventsStoryQuery_graphql.node, convertResponse);

var useLoader = RescriptRelay_Query.useLoader(convertVariables, EventsStoryQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(EventsStoryQuery_graphql.node, convertResponse, (function (prim) {
        return prim;
      }));

var $$fetch = RescriptRelay_Query.$$fetch(EventsStoryQuery_graphql.node, convertResponse, convertVariables);

var fetchPromised = RescriptRelay_Query.fetchPromised(EventsStoryQuery_graphql.node, convertResponse, convertVariables);

var retain = RescriptRelay_Query.retain(EventsStoryQuery_graphql.node, convertVariables);

var EventsStoryQuery = {
  Operation: undefined,
  Types: undefined,
  convertVariables: convertVariables,
  convertResponse: convertResponse,
  convertWrapRawResponse: convertWrapRawResponse,
  use: use,
  useLoader: useLoader,
  usePreloaded: usePreloaded,
  $$fetch: $$fetch,
  fetchPromised: fetchPromised,
  retain: retain
};

export {
  EventsStoryQuery ,
}
/* use Not a pure module */
