// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lingui from "../../locales/Lingui.mjs";
import * as RelayEnv from "../../entry/RelayEnv.mjs";
import * as Localized from "../shared/i18n/Localized.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as DefaultLayout from "../pages/DefaultLayout.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as DefaultLayoutQuery_graphql from "../../__generated__/DefaultLayoutQuery_graphql.mjs";

import { css, cx } from '@linaria/core'
;

import { t } from '@lingui/macro'
;

function loadMessages(lang) {
  var tmp = lang === "ja" ? import("../../locales/src/components/organisms/Nav/ja") : import("../../locales/src/components/organisms/Nav/en");
  return [tmp.then(function (messages) {
                React.startTransition(function () {
                      Lingui.i18n.load(lang, messages.messages);
                    });
              })];
}

var LoaderArgs = {};

async function loader(param) {
  return ReactRouterDom.defer({
              data: Core__Option.map(RelayEnv.getRelayEnv(param.context, import.meta.env.SSR), (function (env) {
                      return DefaultLayoutQuery_graphql.load(env, undefined, "store-or-network", undefined, undefined);
                    })),
              i18nLoaders: Caml_option.some(Localized.loadMessages(param.params.lang, loadMessages))
            });
}

var HydrateFallbackElement = JsxRuntime.jsx("div", {
      children: "Loading fallback..."
    });

var Component = DefaultLayout.make;

export {
  Component ,
  loadMessages ,
  LoaderArgs ,
  loader ,
  HydrateFallbackElement ,
}
/*  Not a pure module */
