// Generated by ReScript, PLEASE EDIT WITH CARE

import PreloadInsertingStreamNodeJs from "./PreloadInsertingStreamNode.js";

function make(prim) {
  return new PreloadInsertingStreamNodeJs(prim);
}

var $$Node = {
  make: make
};

export {
  $$Node ,
}
/* ./PreloadInsertingStreamNode.js Not a pure module */
