// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as React from "@lingui/react";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";

function LangSwitch$LocaleButton(props) {
  var locale = props.locale;
  if (props.active) {
    return JsxRuntime.jsx("span", {
                children: locale.display
              });
  } else {
    return JsxRuntime.jsx(ReactRouterDom.Link, {
                to: "/" + locale.locale + props.path,
                children: JsxRuntime.jsx("span", {
                      children: locale.display
                    })
              });
  }
}

var LocaleButton = {
  make: LangSwitch$LocaleButton
};

var locales = [
  {
    locale: "en",
    display: "English"
  },
  {
    locale: "jp",
    display: "日本語"
  }
];

function LangSwitch(props) {
  var match = React.useLingui();
  var locale = match.i18n.locale;
  var match$1 = ReactRouterDom.useLocation();
  var basePath = match$1.pathname.replace(new RegExp("^/" + locale), "");
  return Belt_Array.mapWithIndex(locales, (function (index, loc) {
                return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                            children: [
                              index > 0 ? " | " : null,
                              JsxRuntime.jsx(LangSwitch$LocaleButton, {
                                    locale: loc,
                                    path: basePath,
                                    active: loc.locale === locale
                                  })
                            ]
                          });
              }));
}

var make = LangSwitch;

var $$default = LangSwitch;

export {
  LocaleButton ,
  locales ,
  make ,
  $$default as default,
}
/* @lingui/react Not a pure module */
