// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function LoginLink(props) {
  return JsxRuntime.jsx("a", {
              children: t`login with Line`,
              className: props.className,
              href: "/oauth-login"
            });
}

var make = LoginLink;

export {
  make ,
}
/*  Not a pure module */
