// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function FormSection(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: props.title,
                      className: "text-base font-semibold leading-7 text-gray-900"
                    }),
                Core__Option.getOr(Core__Option.map(props.description, (function (description) {
                            return JsxRuntime.jsx("p", {
                                        children: description,
                                        className: "mt-1 text-sm leading-6 text-gray-600"
                                      });
                          })), null),
                props.children
              ],
              className: "border-b border-gray-900/10 pb-12"
            });
}

var make = FormSection;

export {
  make ,
}
/*  Not a pure module */
