// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function FormSection(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: t`Details`,
                      className: "text-base font-semibold leading-7 text-gray-900"
                    }),
                JsxRuntime.jsx("p", {
                      children: props.title,
                      className: "mt-1 text-sm leading-6 text-gray-600"
                    }),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6"
                    })
              ],
              className: "border-b border-gray-900/10 pb-12"
            });
}

var make = FormSection;

export {
  make ,
}
/*  Not a pure module */
