// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import { css, cx } from '@linaria/core'
;

function Footer(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: "Copyright the Racquet League Club",
                    className: "grid grid-cols-1 gap-4 text-xs leading-5"
                  }),
              className: "border-t py-3 mt-3"
            });
}

var make = Footer;

var $$default = Footer;

export {
  make ,
  $$default as default,
}
/*  Not a pure module */
