// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import { css, cx } from '@linaria/core'
;

var style = (css`
        @apply container mx-auto px-4 sm:px-6 lg:px-8;
      `);

function Nav$LayoutContainer(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: style
            });
}

var LayoutContainer = {
  style: style,
  make: Nav$LayoutContainer
};

function Nav(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("header", {
                    children: JsxRuntime.jsx("nav", {
                          children: JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx("a", {
                                      children: JsxRuntime.jsx("span", {
                                            children: "Racquet League"
                                          }),
                                      href: "/"
                                    })
                              })
                        })
                  })
            });
}

var make = Nav;

var $$default = Nav;

export {
  LayoutContainer ,
  make ,
  $$default ,
  $$default as default,
}
/*  Not a pure module */
