// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lingui from "../../locales/Lingui.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function ViewerRsvpStatus(props) {
  if (props.joined) {
    return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                children: [
                  JsxRuntime.jsx("em", {
                        children: (t`You are going to this event`)
                      }),
                  " ",
                  JsxRuntime.jsx("a", {
                        children: (t`Leave event`),
                        onClick: props.onLeave
                      })
                ]
              });
  } else {
    return JsxRuntime.jsx("a", {
                children: (t`Join event`),
                onClick: props.onJoin
              });
  }
}

function loadMessages(lang) {
  var tmp = lang === "jp" ? import("../../locales/jp/organisms/ViewerRsvpStatus.mjs") : import("../../locales/en/organisms/ViewerRsvpStatus.mjs");
  return [tmp.then(function (messages) {
                Lingui.i18n.load(lang, messages.messages);
              })];
}

var make = ViewerRsvpStatus;

var $$default = ViewerRsvpStatus;

export {
  make ,
  loadMessages ,
  $$default as default,
}
/*  Not a pure module */
